cp -f camelcase.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f flexies-zonder-basiswoord.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f rapportage-fouten-met-correcties.html /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-flexies.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-woorden-behalve-fout.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f nieuwe-woorden-basiswoord-te-keuren.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f nieuwe-woorden-basiswoord-ongekeurd.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f nieuwe-woorden-deel-van.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f nieuwe-woorden-flexievorm.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f nieuwe-woorden-fout.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-woorden-kandidaat-verwijdering.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-nieuwe-flexies.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f hoofdletterschrijfwijze.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f meer-dan-een-alternatief.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f flexies-met-basiswoord.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f meeste-klinkers.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f ij-geen-lange-ij.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f fi-ligatuur-ongewenst.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f ffi-ligatuur-ongewenst.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-blijvende-basiswoorden.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f voorheen-fout.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f impliciete-flexies.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-voorheen-flexie.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f voorheen-gekeurd.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f uitzonderingen.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f wijzigingen.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f te-keuren.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f k-met-hoofdletter-voorheen-B.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f K-met-hoofdletter-voorheen-B.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-fout-abnormaal.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-fout-normaal.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-fout.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f toegestane-speciale-karakters.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f toegestane-zeer-speciale-karakters.tsv /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-nieuwe-te-keuren-basiswoorden.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-nieuwe-woorden-uit-fouten.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-basiswoorden.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-basiswoorden-uit-flexievormen.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-nieuwe-basiswoorden-uit-flexievormen.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-goed.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-nieuwe-woorden-uit-alternatieven.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-woorden-uit-fouten.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-woorden-uit-alternatieven.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
cp -f alle-flexies-met-apostrof-zonder-basis.txt /var/www/opentaal.nl/www/htdocs/eindredactie/
